services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./Backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./APPUI
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./APPUI:/app
    depends_on:
      - backend
    networks:
      - app-network
      
  text2sql:
    build: 
      context: ./text2sql_module
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge